### ISSUE TITLE
Incorporate documentation into website

### ISSUE THREAD

**Issue by yippyskippy** [katzenpost/katzenpost#457]
Given the website revamp there is the task to [re-add the documentation](/katzenpost/website/issues/28). Previously when `katzenpost/docs` repo was used, this was easily done as a git submodule, but due to the monorepoification, using sub-module is not to straight forward and might not be possible, given steps to clone to a single folder:

- [How can I clone only a subfolder of a Git repository and make all the files in the subfolder end up in the root?](https://stackoverflow.com/questions/23833436/how-can-i-clone-only-a-subfolder-of-a-git-repository-and-make-all-the-files-in-t)
- [How do I clone a subdirectory only of a Git repository?](https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository)
- [How to Turn a Turn a Directory in a Git Repository Into a Submodule](https://www.howtogeek.com/devops/how-to-turn-a-turn-a-directory-in-a-git-repository-into-a-submodule/)

@leif since you drove the monorepo effort- is there a technical reason to have not rather included [katzenpost/docs](/katzenpost/docs) repo here as a sub-module but instead added it to tree?

```[tasklist]
### Tasks
- [x] Convert docs .rst to .md files for Hugoification
- [x] Add appropriate frontmatter to .md files
- [x] Determine information architecture of documentation w/ @jdormansteele
```

**Comment by leif** [comment]
The primary reason to have docs in the monorepo is that docs and code can (and sometimes do) get changed together.

Keeping them in the same repo means that whenever a code change necessitates a docs change, those changes can be developed and reviewed and ultimately merged simultaneously. Having multiple monorepo branches each have their own in-progress documentation seems simpler than needing to keep track of corresponding branches in a separate repo.

The reason I see why we might *not* want to keep docs in the monorepo would be because it is irritating to need to wait for CI to run when making a minor change to the docs which we know shouldn't affect the tests anyway. But, I don't think anybody would really object to clicking the "bypass restrictions" button to merge a docs-only PR without waiting for CI in that case.

So, in my opinion we should keep the docs in the monorepo. But maybe I'm missing another reason to take them out?
